# Generated by Django 3.0.4 on 2020-10-03 09:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category_3D',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200, unique=True, verbose_name='Kategoriya nomi')),
            ],
            options={
                'verbose_name_plural': 'Kategoriyalar',
                'ordering': ['category_name'],
            },
        ),
        migrations.CreateModel(
            name='Modul_Format_3D',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modul_constructor', models.CharField(max_length=100, unique=True, verbose_name='Konstruktor Dastur')),
                ('modul_extension', models.CharField(blank=True, max_length=10, null=True, verbose_name='Modul Farmati')),
            ],
            options={
                'verbose_name_plural': 'Konstruktor Dasturlar',
                'ordering': ['modul_constructor'],
            },
        ),
        migrations.CreateModel(
            name='Info_Modul_3D',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modul_file', models.FileField(upload_to='moduls/%Y/%m/%d/', verbose_name='3D Modul Fayli')),
                ('modul_images', models.ImageField(upload_to='images/', verbose_name='3D Modul Rasmi')),
                ('modul_name', models.CharField(max_length=300, verbose_name='3D Modul Nomi')),
                ('modul_description', models.TextField(verbose_name='Tarif')),
                ('modul_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(100000000)], verbose_name='3D Modul Narxi')),
                ('price_currency', models.CharField(choices=[(None, ''), ("so'm", "so'm"), ('$', 'dollor'), ('euro', 'euro'), ('ruble', 'ruble')], default='', max_length=50, verbose_name='Valyuta Turi')),
                ('state_active', models.BooleanField(default=True)),
                ('modul_animated', models.BooleanField(default=False)),
                ('modul_printable', models.BooleanField(default=False)),
                ('modul_author_name', models.CharField(max_length=150, verbose_name='Muallif ismi')),
                ('modul_published', models.DateTimeField(auto_now_add=True)),
                ('modul_updated', models.DateTimeField(auto_now=True)),
                ('modul_format', models.ManyToManyField(to='product.Modul_Format_3D')),
                ('modul_primary_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modul_primary_category', to='product.Category_3D')),
                ('modul_secondary_categories', models.ManyToManyField(related_name='modul_secondary_category', to='product.Modul_Format_3D')),
            ],
            options={
                'verbose_name': '3D Modul Malumotlari',
                'verbose_name_plural': '3D Modul Malumotlari',
                'ordering': ['modul_published', 'modul_updated'],
            },
        ),
    ]
