# Generated by Django 3.0.4 on 2020-10-03 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info_modul_3d',
            name='modul_secondary_categories',
            field=models.ManyToManyField(related_name='modul_secondary_category', to='product.Category_3D'),
        ),
    ]
