# Generated by Django 3.0.4 on 2020-10-03 10:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20201003_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info_modul_3d',
            name='modul_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100000000)], verbose_name='3D Modul Narxi'),
        ),
    ]
