# Generated by Django 3.0.4 on 2020-10-03 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20201003_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modul_format_3d',
            name='modul_constructor',
            field=models.CharField(max_length=100, unique=True, verbose_name='Konstruktor Dasturlar'),
        ),
    ]
